IF NOT EXISTS(SELECT * FROM sysobjects WHERE name='papeis' and xtype='U')

create table papeis(
	
ID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
NOME_PAPEL VARCHAR(45) NOT NULL,
DESCRICAO_PAPEL VARCHAR(200) NULL,
COD_STATUS_PAPEL BIT NULL


);