IF NOT EXISTS(SELECT * FROM sysobjects WHERE name='USUARIOS_PAPEIS' and xtype='U')


	
CREATE TABLE USUARIOS_PAPEIS(
	USUARIO_ID BIGINT NOT NULL,
	PAPEL_ID BIGINT NOT NULL,
	CONSTRAINT FK_USUARIOS_PAPEIS_USUARIO_ID FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID),
	CONSTRAINT FK_USUARIOS_PAPEIS_PAPEL_ID FOREIGN KEY (PAPEL_ID) REFERENCES PAPEIS(ID),





);